### ISSUE TITLE
CAM012 Kieran West Speakers

### ISSUE THREAD

**Issue by colmcmurphy** [13enedict/CCRC#22]
The middle speaker near where 3 sits does not work. Instructions from the cox cannot be heard clearly.

**Comment by 13enedict** [comment]
The speaker itself is functional but had come loose from it's bracket. The problem was with the wiring loom which is frayed and damaged. I have made a very temporary repair to the loom which should allow it to work for now. 

I have also remounted the speaker. I noticed that the other two speakers are close to coming loose as well but we currently lack the spare parts to properly secure them

**Comment by 13enedict** [comment]
Replaced the wiring loom so the speaker should be fine now. We still need some spare parts for the other speakers, though

**Comment by colmcmurphy** [comment]
Cheers Benedict.

**Comment by 13enedict** [comment]
Finally added missing wing nuts to speakers and can close \o/
