### ISSUE TITLE
Rechargeable batteries for ergos

### ISSUE THREAD

**Issue by Git-Oryx** [13enedict/CCRC#3]
Provide the boathouse ergs with re-chargeable batteries for the PM# Monitors.

Some good quality long lasting ones if possible.

Suggested items:
- [Maha MH-D110] (http://www.amazon.co.uk/dp/B0002LR50A) Super High Power 11,000mAh
- Powerex MH-C808M Charger

**Comment by 13enedict** [comment]
OK, I'm looking in to this. Ni-MH batteries tend to be quite bad for this type of application because of relatively high self discharge rates. Panasonic Eneloop are generally considered the best kind with very low self discharge rates but their D size batteries are only sold in Japan and Singapore.

With this in mind, my plan is to get 3AA to D battery adapters. These allow you to use 3 AA Eneloop batteries in parallel in place of a single D battery. Total capacity will be about 6Ah which is lower but I think this will be quite a versatile solution as you can use 1 or 2 AAs in place of a D.

Finally, this is cheaper, 8 Eneloop batteries can be bought for £15.

**Comment by 13enedict** [comment]
We have the batteries now, I've fitted them to one erg. I'll do the others soon.
