### ISSUE TITLE
Liberty Quad Wing Riggers (10mm nuts or 4mm hex screws)

### ISSUE THREAD

**Issue by Git-Oryx** [13enedict/CCRC#319]
Liberty

Pretty much it needs either some new screws or use washers between the wing riggers and the gunwale.
The current washer/screw types are warn out and not threaded, so unable to rig it correctly.

Might be worth having a look at first and then deciding which screws to use with it.  Also some washer screws are missing.  Best if it's all the standard 10mm nuts and bolts.

**Comment by NSinclair94** [comment]
There is a spares box at Ely with some fixings in, there should be some in
there.

On 13 Jan 2019 00:54, "Git-Oryx" <notifications@github.com> wrote:

Liberty

Pretty much it needs either some new screws or use washers between the wing
riggers and the gunwale.
The current washer/screw types are warn out and not threaded, so unable to
rig it correctly.

Might be worth having a look at first and then deciding which screws to use
with it. Also some washer screws are missing. Best if it's all the standard
10mm nuts and bolts.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CityRC/Equipment/issues/319>, or mute the thread
