### ISSUE TITLE
CAM113 Green Stämpfli Footplate 

### ISSUE THREAD

**Issue by LauraClack** [13enedict/CCRC#61]
HI Benedict,

The green pair needs a new stroke footplate - lots of the holes have worn through on one side. I forgot to look after the outing to see if you had one the correct size. Happy to fit it if you can order one from Stampfli.

Ta

Laura

**Comment by JackLA** [comment]
These are extra narrow plates that I don't think are standard so will need
measuring, I also think it might need some new shoes!

**Comment by LauraClack** [comment]
Stroke shoes look pretty new but the bow ones could do with some attention. The slightly adjustable ones are pretty ideal for this boat as it's used by men and women.
Ta
Laura

Date: Mon, 21 Mar 2016 05:03:28 -0700

**Comment by 13enedict** [comment]
OK, I'll see if we have any footplates that fit and if not get some from Neaves so we can fit their adjustable shoes. We have sizes 4-8 and 8-12 spare shoes but we can potentially get other sizes for this sort of thing. I was thinking of perhaps 7-11 or 6-10 for boats used by men and women...

**Comment by LauraClack** [comment]
8-12 prob best for that boat, they do come up a little small anyway.

**Comment by 13enedict** [comment]
OK, it takes the same size footplates as CAM321 Redeham and Weep. Well, sort of, they're the same specification but actually a couple of mm narrower. I had to sand a shoe plate down to make it fit. It, along with the nuts, are in workshop. Why are the nuts not on the boat, you may ask? Because I forgot and couldn't be bothered to put them back in.

**Comment by 13enedict** [comment]
The nuts are in a bag in the left shoe
